name: 'ggshield sca scan'
description: 'Scan commits for sca vulnerabilities'
author: GitGuardian <support@gitguardian.com>

inputs:
  args:
    description: |
      Arguments to pass to `ggshield sca scan ci`.

      [`ggshield sca scan ci` reference](https://docs.gitguardian.com/ggshield-docs/reference/sca/scan/ci).
    required: false
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'docker://gitguardian/ggshield:v1.32.0'
  entrypoint: '/app/docker/actions-sca-entrypoint.sh'
  args:
    - ${{ inputs.args }}
