stages:
  - test

.core_test: &core_test
  stage: test
  before_script:
    - pipenv install --system --ignore-pipfile --dev
  except:
    refs:
      - tags
      - preprod
      - prod

include:
  - project: "gg-code/gitlab-ci-templates"
    file: "/python-3.8.tests.yml"
# override template for python tests

🧀 dependency_scan:pipenv:
  <<: *core_test

🧀 back:lint:
  <<: *core_test
