image: gitguardian/ci:latest
stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - pipenv install --dev
  script:
    - pipenv run pytest --disable-pytest-warnings -vvv


lint:
  stage: test
  before_script:
    - pipenv install --dev
  script:
    - pipenv run flake8
    - pipenv run black --config black.toml --check **/*.py


deploy:
  stage: deploy
  before_script:
    - pipenv install --dev
    - pipenv install twine
  script:
    - pipenv run python setup.py sdist bdist_wheel
    - pipenv run twine upload --repository-url https://${PYPI_HOST} dist/*.gz -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
  only:
    refs:
      - dev
