- id: commit-ggshield
  name: GitGuardian Shield (pre-commit)
  language: python
  entry: ggshield
  args: ['scan', '-m', 'pre-commit']
- id: ggshield
  name: GitGuardian Shield (pre-commit)
  language: python
  entry: ggshield
  args: ['scan', '-m', 'pre-commit']
- id: docker-ggshield
  name: GitGuardian Shield (docker)
  language: docker_image
  entry: -e GITGUARDIAN_API_KEY gitguardian/ggshield:latest ggshield scan -m pre-commit
