name: 'ggshield Local Action'
description: 'Scan commits for policy breaks (using repository image)'
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - scan
    - -v
    - --mode=ci
