name: 'ggshield Local Action'
description: 'Scan commits for policy breaks (using repository image)'
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
    GITGUARDIAN_API_URL: ${{ secrets.GITGUARDIAN_API_URL }}
  args:
    - ggshield
    - scan
    - -v
    - --mode=ci
