name: 'ggshield Local Action'
description: 'Scan commits for security incidents (using repository image)'
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ggshield
    - -v
    - scan
    - ci
