-   repo: local
    hooks:
    -   id: ggshield
        name: GitGuardian Shield
        entry: ggshield scan -m pre-commit
        language: python
        language_version: python3
        stages: [commit]

