name: 'ggshield iac scan'
description: 'Scan commits for iac vulnerabilities'
author: GitGuardian <support@gitguardian.com>

inputs:
  args:
    description: |
      Arguments to be passed to ggshield iac scan
      Options:
        --exit-zero                     Always return a 0 (non-error) status code, even if issues
                                        are found. The env var GITGUARDIAN_EXIT_ZERO can also be used
                                        to set this option.
        --minimum-severity              [LOW|MEDIUM|HIGH|CRITICAL]
                                        Minimum severity of the policies
        --ignore-policy, --ipo TEXT     Policies to exclude from the results.
        --ignore-path, --ipa PATH       Do not scan the specified paths.
        --json                          JSON output.
    required: false
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: '../../Dockerfile'
  entrypoint: '/app/docker/actions-iac-entrypoint.sh'
  args:
    - ${{ inputs.args }}
