name: 'ggshield iac scan'
description: 'Scan commits for iac vulnerabilities'
author: GitGuardian <support@gitguardian.com>

inputs:
  args:
    description: |
      Arguments to pass to `ggshield iac scan ci`.

      [`ggshield iac scan ci` reference](https://docs.gitguardian.com/ggshield-docs/reference/iac/scan/ci).
    required: false
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'docker://gitguardian/ggshield:v1.18.1'
  entrypoint: '/app/docker/actions-iac-entrypoint.sh'
  args:
    - ${{ inputs.args }}
