#!/usr/bin/env bash
set -euo pipefail

# otherwise grep -P in pack chocolatey/pack script fails on Windows
export LC_ALL=en_US.utf8

# parse command line arguments
zip_name=$1
output_dir=$2

# unzip to folder
if ! command -v unzip > /dev/null ; then
    apt update
    apt install unzip
fi
mkdir win_package
unzip $zip_name -d win_package

version=$(echo "$zip_name" | grep -oP '(?<=ggshield-)[0-9.]+')

# choco-package will contain everything needed to build the nupkg
mkdir choco-package
mkdir choco-package/tools

mv win_package/*/_internal choco-package/tools
mv win_package/*/ggshield.exe choco-package/tools
cp scripts/chocolatey/ggshield.nuspec choco-package
cp scripts/chocolatey/VERIFICATION.txt choco-package/tools
cp LICENSE choco-package/tools/LICENSE.txt
sed -i "s/__VERSION__/$version/" choco-package/ggshield.nuspec

choco pack choco-package/* --version $version --outdir $output_dir

rm -rf win_package choco-package
