#!/usr/bin/env bash
set -euo pipefail
# AUTOGENERATED FILE, DO NOT EDIT!
# This file has been generated by the `action-entrypoint-generator` script
# defined in `scripts/action-entrypoint-generator`. To make changes to this
# file, modify the script and rerun it.

# GitHub overrides $HOME. Set it back to the home directory of our `app` user,
# otherwise the call to `git config` fails.
export HOME=/home/app

# Mark the current directory as safe. If we don't do this, git commands fail
# because the source in $PWD is owned by a different user than our `app` user.
git config --global --add safe.directory "$PWD"

progress() {
    echo -e "\033[34m$*\033[0m"
}

update_ggshield() {
    local old_pwd="$PWD"

    cd "$HOME"
    local venv_dir=$HOME/venv

    progress "Cloning ggshield $GITGUARDIAN_GGSHIELD_REF"
    git clone --depth 1 https://github.com/gitguardian/ggshield
    cd ggshield
    git fetch origin "$GITGUARDIAN_GGSHIELD_REF"
    git checkout FETCH_HEAD

    progress "Creating venv in $venv_dir"
    python -m venv "$venv_dir"
    . "$venv_dir/bin/activate"

    progress "Installing in venv"
    pip install .

    cd "$old_pwd"

    progress "ggshield=$(which ggshield)"
}

if [ -n "${GITGUARDIAN_GGSHIELD_REF:-}" ] ; then
    update_ggshield
else
    progress "Using ggshield from image"
fi

args=("$@")
ggshield secret scan -v ${args[@]} ci
