#!/usr/bin/env bash
set -euo pipefail

PROGNAME=$(basename "$0")
SCRIPT_DIR=$(cd "$(dirname "$0")" ; pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/../.." ; pwd)

DEFAULT_STEPS="req build copy_files test sign create_archive"

PYINSTALLER_OUTPUT_DIR=$ROOT_DIR/dist/ggshield
PACKAGES_DIR=$ROOT_DIR/packages

REQUIREMENTS="pyinstaller"

# Whether we want a signed binary or not
DO_SIGN=0

MACOS_P12_FILE=${MACOS_P12_FILE:-}
MACOS_P12_PASSWORD_FILE=${MACOS_P12_PASSWORD_FILE:-}

# Path to a file used by rcodesign for notarizing.
# Follow the instructions from
# https://gregoryszorc.com/docs/apple-codesign/0.27.0/apple_codesign_getting_started.html#apple-codesign-app-store-connect-api-key
# to generate one.
MACOS_API_KEY_FILE=${MACOS_API_KEY_FILE:-}

# Colors
C_RED="\e[31;1m"
C_GREEN="\e[32;1m"
C_RESET="\e[0m"

err() {
    echo "$@" >&2
}

info() {
    printf "$C_GREEN%s$C_RESET\n" "$PROGNAME: [INFO] $*" >&2
}

die() {
    printf "$C_RED%s$C_RESET\n" "$PROGNAME: [ERROR] $*" >&2
    exit 1
}

usage() {
    if [ "$*" != "" ] ; then
        err "Error: $*"
        err
    fi

    cat << EOF
Usage: $PROGNAME [OPTION ...] [STEPS]
Build OS specific packages for ggshield.

Default steps are: $DEFAULT_STEPS

Options:
  -h, --help      Display this usage message and exit.
  --sign          Sign the binary, on supported OSes.

For more details, see doc/dev/os-packages.md.
EOF

    exit 1
}

read_version() {
    VERSION=$(grep -o "[0-9]*\.[0-9]*\.[0-9]*" "$ROOT_DIR/ggshield/__init__.py")
}

init_system_vars() {
    local arch
    arch=$(uname -m)

    case "$arch" in
    arm64)
        HUMAN_ARCH=ARM-based
        ;;
    x86_64)
        HUMAN_ARCH=Intel-based
        ;;
    *)
        die "Unsupported architecture '$arch'"
        ;;
    esac

    local out
    out=$(uname)

    # directory containing ggshield executable, inside the archive
    INSTALL_PREFIX=""

    case "$out" in
    Linux)
        EXE_EXT=""
        TARGET="$arch-unknown-linux-gnu"
        HUMAN_OS=Linux
        ;;
    Darwin)
        EXE_EXT=""
        HUMAN_OS=macOS
        TARGET="$arch-apple-darwin"
        if [ "$DO_SIGN" -eq 1 ] ; then
            REQUIREMENTS="$REQUIREMENTS rcodesign"
            DEFAULT_STEPS="$DEFAULT_STEPS notarize"
        fi
        INSTALL_PREFIX=opt/gitguardian/ggshield-$VERSION
        ;;
    MINGW*|MSYS*)
        EXE_EXT=".exe"
        HUMAN_OS=Windows
        TARGET="$arch-pc-windows-msvc"
        ;;
    *)
        die "Unknown OS. uname printed '$out'"
        ;;
    esac
    ARCHIVE_DIR_NAME=ggshield-$VERSION-$TARGET
}

step_req() {
    local fail=0
    info "Checking requirements"
    local requirements=$REQUIREMENTS
    for exe in $requirements ; do
        err -n "$exe: "
        if command -v "$exe" > /dev/null ; then
            err OK
        else
            err FAIL
            fail=1
        fi
    done
    if [ $fail -ne 0 ] ; then
        die "Not all requirements are installed"
    fi
}

step_build() {
    rm -rf build/ggshield
    rm -rf "$PYINSTALLER_OUTPUT_DIR"

    pyinstaller ggshield/__main__.py --name ggshield --noupx
}

step_copy_files() {
    if ! [ -d "$PYINSTALLER_OUTPUT_DIR" ] ; then
        die "$PYINSTALLER_OUTPUT_DIR does not exist"
    fi
    local pyinstaller_ggshield=$PYINSTALLER_OUTPUT_DIR/ggshield$EXE_EXT
    if ! [ -f "$pyinstaller_ggshield" ] ; then
        die "Can't find '$pyinstaller_ggshield', maybe 'build' step did not run?"
    fi

    mkdir -p "$PACKAGES_DIR"
    case "$HUMAN_OS" in
    Linux|Windows)
        local output_dir="$PACKAGES_DIR/$ARCHIVE_DIR_NAME"
        info "Copying files to $output_dir"
        rm -rf "$output_dir"
        cp -R "$PYINSTALLER_OUTPUT_DIR" "$output_dir"

        info "Generating README.md"
        sed \
            -e "s/@HUMAN_OS@/$HUMAN_OS/" \
            -e "s/@HUMAN_ARCH@/$HUMAN_ARCH/" \
            "$SCRIPT_DIR/README.md.tmpl" \
            > "$output_dir/README.md"
        ;;
    macOS)
        local output_dir="$PACKAGES_DIR/$ARCHIVE_DIR_NAME/$INSTALL_PREFIX"
        local bin_dir="$PACKAGES_DIR/$ARCHIVE_DIR_NAME/usr/local/bin"
        info "Copying files to $output_dir"
        rm -rf "$output_dir" "$bin_dir"
        mkdir -p "$(dirname $output_dir)"
        cp -R "$PYINSTALLER_OUTPUT_DIR" "$output_dir"

        info "Creating launcher symlink"
        mkdir -p "$bin_dir"
        ln -s "/$INSTALL_PREFIX/ggshield" "$bin_dir/ggshield"
        ;;
    esac
}

sign_file() {
    if [ -z "$MACOS_P12_FILE" ] ; then
        die "\$MACOS_P12_FILE must be set to sign"
    fi
    local file
    file="$1"
    info "- Signing $file"
    rcodesign sign \
        --p12-file "$MACOS_P12_FILE" \
        --p12-password-file "$MACOS_P12_PASSWORD_FILE" \
        --code-signature-flags runtime \
        --for-notarization \
        "$file"
}

list_files_to_sign() {
    local archive_dir="$PACKAGES_DIR/$ARCHIVE_DIR_NAME"
    echo "$archive_dir/$INSTALL_PREFIX/ggshield"
    find "$archive_dir" -name '*.so' -o -name '*.dylib'
}

step_sign() {
    if [ "$HUMAN_OS" != "macOS" ] ; then
        info "Signing not supported on $HUMAN_OS, skipping step"
        return
    fi
    if [ "$DO_SIGN" -eq 0 ] ; then
        info "Skipping signing step"
        return
    fi
    list_files_to_sign | while read path ; do
        sign_file "$path"
    done
}

step_test() {
    for args in --help --version ; do
        info "test: running $args"
        "$PACKAGES_DIR/$ARCHIVE_DIR_NAME/$INSTALL_PREFIX/ggshield${EXE_EXT}" $args
        info "test: running $args: OK"
    done
}

step_functests() {
    PATH=$PACKAGES_DIR/$ARCHIVE_DIR_NAME/$INSTALL_PREFIX:$PATH pytest tests/functional
}

step_create_archive() {
    local archive_path
    cd "$PACKAGES_DIR"
    case "$HUMAN_OS" in
    Linux)
        archive_path="$PACKAGES_DIR/$ARCHIVE_DIR_NAME.tar.gz"
        tar -czf "$archive_path" "$ARCHIVE_DIR_NAME"
        ;;
    macOS)
        archive_path="$PACKAGES_DIR/$ARCHIVE_DIR_NAME.pkg"
        pkgbuild \
            --identifier com.gitguardian.ggshield \
            --version "$VERSION" \
            --root "$PACKAGES_DIR/$ARCHIVE_DIR_NAME" \
            "$archive_path"

        if [ "$DO_SIGN" -eq 1 ] ; then
            sign_file "$archive_path"
        fi
        ;;
    Windows)
        archive_path="$PACKAGES_DIR/$ARCHIVE_DIR_NAME.zip"
        7z a "$archive_path" "$ARCHIVE_DIR_NAME"
        ;;
    esac
    cd -
    info "Archive created in $archive_path"
}

step_notarize() {
    if [ "$DO_SIGN" -eq 0 ] ; then
        info "Skipping notarize step"
    fi
    info "Notarizing"
    rcodesign notary-submit \
        --api-key-file "$MACOS_API_KEY_FILE" \
        --staple \
        "$PACKAGES_DIR/$ARCHIVE_DIR_NAME.pkg"
}

steps=""
while [ $# -gt 0 ] ; do
    case "$1" in
    -h|--help)
        usage
        ;;
    --sign)
        DO_SIGN=1
        ;;
    -*)
        usage "Unknown option '$1'"
        ;;
    *)
        steps="$steps $1"
        ;;
    esac
    shift
done

cd "$ROOT_DIR"
read_version
init_system_vars

if [ -z "$steps" ] ; then
    steps=$DEFAULT_STEPS
fi
info "Steps: $steps"

for step in $steps ; do
    info "step $step"
    "step_$step"
done
info "Success!"
