#!/usr/bin/env bash
# This script updates our Pipfile.lock.
# The Python version is defined in the Dockerfile.
set -euo pipefail

IMAGE_NAME=ggshield-update-pipfile-lock

SCRIPT_DIR=$(dirname $0)

cd $SCRIPT_DIR
docker build -t $IMAGE_NAME --build-arg UID=$UID .

# Move to the work-tree root
cd $(git rev-parse --show-toplevel)
docker run -v $PWD:/home/user/src $IMAGE_NAME
