name: Update Downstream Dependents

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        type: string

jobs:
  update-ggshield-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repository:
          - GitGuardian/gitguardian-vscode
          - GitGuardian/ggshield-azure-devops-extension
    name: ${{ matrix.repository }}
    steps:
      - name: Checkout ${{ matrix.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          token: ${{ secrets.PAT_GITHUB }}
          sparse-checkout: |
            ggshield_version
          sparse-checkout-cone-mode: false

      - name: Create branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b update-ggshield-to-${{ steps.version.outputs.value }}

      - name: Update ggshield_version file
        run: |
          echo "${{ steps.version.outputs.value }}" > ggshield_version

      - name: Commit changes
        run: |
          git add ggshield_version
          git commit -m "Update ggshield version to ${{ steps.version.outputs.value }}"

      - name: Push changes
        run: |
          git push --set-upstream origin update-ggshield-to-${{ steps.version.outputs.value }} --force

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          gh pr create \
            --repo ${{ matrix.repository }} \
            --title "Update ggshield version to ${{ steps.version.outputs.value }}" \
            --body "This PR updates ggshield to version ${{ steps.version.outputs.value }}. This update was automatically generated by a workflow on the ggshield repository." \
            --base main \
            --head update-ggshield-to-${{ steps.version.outputs.value }}
